import { formatClaimCurrency } from "@/features/claims/services/claim-display.service";

type ClaimEstimateInsightProps = {
  adjusterNotes: string | null;
  lineItems: Record<string, unknown>[] | null;
  totalAmount: number | null;
};

type EstimateLineItemView = {
  confidence: string | null;
  damageType: string | null;
  estimatedCost: number | null;
  label: string;
  rationale: string | null;
  repairAction: string | null;
  severity: string | null;
  source: string | null;
  vehicleArea: string | null;
};

function readString(record: Record<string, unknown>, key: string) {
  const value = record[key];
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function readNumber(record: Record<string, unknown>, key: string) {
  const value = record[key];
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}

function formatToken(value: string | null) {
  if (!value) {
    return null;
  }

  return value
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function normalizeLineItems(lineItems: Record<string, unknown>[] | null) {
  return (lineItems ?? []).map((lineItem) => {
    const label = readString(lineItem, "label");
    const vehicleArea = readString(lineItem, "vehicleArea");
    const damageType = readString(lineItem, "damageType");

    return {
      confidence: readString(lineItem, "confidence"),
      damageType,
      estimatedCost: readNumber(lineItem, "estimatedCost"),
      label: label || [formatToken(vehicleArea), formatToken(damageType)].filter(Boolean).join(" ") || "Estimate line item",
      rationale: readString(lineItem, "rationale"),
      repairAction: readString(lineItem, "repairAction"),
      severity: readString(lineItem, "severity"),
      source: readString(lineItem, "source"),
      vehicleArea,
    } satisfies EstimateLineItemView;
  });
}

export function ClaimEstimateInsight({ adjusterNotes, lineItems, totalAmount }: ClaimEstimateInsightProps) {
  const normalizedItems = normalizeLineItems(lineItems);
  const derivedTotal = normalizedItems.reduce((total, item) => total + (item.estimatedCost ?? 0), 0);
  const displayTotal = totalAmount ?? (derivedTotal > 0 ? derivedTotal : null);
  const hasVisibleContent = Boolean(adjusterNotes) || normalizedItems.length > 0 || displayTotal !== null;

  if (!hasVisibleContent) {
    return null;
  }

  const autoGenerated = normalizedItems.some((item) => item.source === "ai_vision");

  return (
    <div className="estimate-insight-stack">
      {adjusterNotes ? (
        <article className="estimate-summary-card">
          <p className="eyebrow">{autoGenerated ? "Computer Vision" : "Estimate Notes"}</p>
          <h5>{autoGenerated ? "Photo-Based Damage Assessment" : "Estimate Summary"}</h5>
          <p className="estimate-summary-copy">{adjusterNotes}</p>
        </article>
      ) : null}

      {normalizedItems.length > 0 ? (
        <div className="estimate-line-item-grid">
          {normalizedItems.map((item, index) => {
            const meta = [formatToken(item.severity), formatToken(item.repairAction), formatToken(item.confidence)]
              .filter(Boolean)
              .join(" | ");

            return (
              <article key={`${item.label}-${index}`} className="estimate-line-item-card">
                <div className="estimate-line-item-head">
                  <div>
                    <h5>{item.label}</h5>
                    {meta ? <p className="estimate-line-item-meta">{meta}</p> : null}
                  </div>
                  <strong>{formatClaimCurrency(item.estimatedCost, "Pending")}</strong>
                </div>
                {item.rationale ? <p className="estimate-line-item-rationale">{item.rationale}</p> : null}
              </article>
            );
          })}
        </div>
      ) : null}

      {displayTotal !== null ? (
        <article className="estimate-total-card">
          <span>{autoGenerated ? "Suggested repair total" : "Current estimate total"}</span>
          <strong>{formatClaimCurrency(displayTotal, "$0")}</strong>
        </article>
      ) : null}
    </div>
  );
}